bitcoin-sv/arc

blocktx/PeerHandler.go

* As it can take many minutes for large blocks to be processed to a block message, give more time for this process before a request is re-sent

Wait a longer until a block request is re-sent

---

metamorph/processor.go

We noticed that transaction took almost 24 hours to confirm. In the code we remove (expire) transactions after 1 hour which means that transactions confirmed after 1 hour will not be able to change their state in database. 
Any consequent status check for the transaction return "SEEN_ON_NETWORK" and not "MINED". That's why we change expiration from 1 hour to 24.

change seen transaction expiration time from an hour to 24 hours

---

blocktx/store/sql/RegisterTransaction.go

We had error in blocktx (issue BPAAS-934) because we incorrectly assumed that the block hash would be present at the point of query. Removed the assumption and query.

remove incorrect block hash query

---

.github/workflows/static-analysis.yml
api/handler/default.go
api/handler/default_test.go
api/helpers.go
go.mod
go.sum
metamorph/Server.go
metamorph/Server_test.go
sonar-project.properties

- Validate the callback URL in both API and metamorph
- This ensures that the user will be informed about his callback URL being invalid
- Otherwise the user could never understand why the callback URL has not been called if the transaction was mined

Validate callback url in API and in metamorph

---

api/handler/load.go
api/transactionHandler/metamorph.go
blocktx/Client.go
cmd/txstatus/main.go
examples/custom/main.go

- If Merkle path not found still return transaction status
- log error
- Return `err` not `ErrTransactionNotFound` in `GetTransactionMerklePath()` blocktx client, as blocktx itself makes this distinction already

If Merkle path not found still return transaction status

---

api/transactionHandler/metamorph.go
blocktx/Server.go
blocktx/interface.go

- log error separately if error is not a `not found` error

fix error logging logic

---

metamorph/Server_test.go
metamorph/processor_mock.go

- Fix the go generate instruction for mocking processor

Fix the go generate instruction for mocking processor

---

api/handler/default.go
api/handler/default_test.go
api/status.go
api/status_test.go
api/transactionHandler/interface.go

- ensure that each transaction api endpoint always returns either a transaction status or a full ErrorFields object
- reduce code duplication of calling `m.processTransactions(tracingCtx, transactionInputs, transactionOptions)` in POSTTransactions() function
- refactor `handleError()` function. returned error was always `nil`
- refactor ErrorField statuses: Remove global variables and replace with constructor
- add unit test coverage for `handleError()`
- remove unused json tags from `TransactionStatus` type

Return err object

---

.github/workflows/go.yml
Makefile
api/test/transactionHandler_mock.go
callbacker/test/utils.go
metamorph/blocktx/mock/mock.go
metamorph/processor_test.go
metamorph/store/mock/mock.go
test/utils.go

- `make install` will install specified versions of code generation tools
- go workflow will make the pipeline fail if running code generation will alter any code. Thereby it is ensured that no generated code has been hand edited.
- update generated go code

Enforce code generation

---

.github/workflows/go.yml
.github/workflows/static-analysis.yml
.github/workflows/static.yml
Makefile
go.mod
go.sum
test/go.mod
test/go.sum

- move both golanci-lint step and staticcheck step into static analysis workflow into separate parallel jobs
- staticcheck cannot run in the same job as actions/setup-go because it causes errors
- golangci lint and staticcheck cannot be in the same job because it cause errors

Rearrange github workflows

---

.gitignore
Makefile

Show the coverage in a tabular way. It also shows a total coverage.
Example
```
+--------------------------------------------------------+--------+---------+-------+---------+---------------+--------------+
|                        Package                         | Blocks | Missing | Stmts | Missing | Block cover % | Stmt cover % |
+--------------------------------------------------------+--------+---------+-------+---------+---------------+--------------+
| github.com/bitcoin-sv/arc/api                          |    381 |     359 |   631 |     576 |          5.77 |         8.72 |
| github.com/bitcoin-sv/arc/blocktx                      |    227 |     176 |   380 |     287 |         22.47 |        24.47 |
| github.com/bitcoin-sv/arc/metamorph/processor_response |     50 |      35 |    88 …
```

Coverage table

---

cmd/metamorph.go
config.yaml
metamorph/processor.go
metamorph/processor_test.go

On loading unmined transactions delete those from storage which have been stored more than 2 weeks earlier

Delete txs from storage after period of time

---

metamorph/server.go

Insert transaction first to update it's status to mined.

Fix for submitting mined transactions

---

metamorph/processor.go

- Do not delete rejected transactions from the processor response map, as they could still get into the mempool and eventually mined
- If rejected transactions stay rejected, they'll get expired and cleaned after (currently) 24h of expiration duration: https://github.com/bitcoin-sv/arc/blob/7046640673b5f348c5a4f6746658c2313ade4c59/metamorph/processor_response_map.go#L59-L63

Do not delete rejected transactions prematurely

---

metamorph/store/dynamodb/dynamodb.go
metamorph/store/dynamodb/dynamodb_test.go

- Do not return an error if the processed at date for a block is not found
- Otherwise block processing will be skipped: https://github.com/bitcoin-sv/arc/blob/17129759f70ac0ca0271c9690bfc6d32c4fc9b53/cmd/metamorph.go#L193-L196
- This reflects the same behaviour as in the badger db implementation: https://github.com/bitcoin-sv/arc/blob/58fb518a00f17514496f6a1e6d6cebe7b3330cdd/metamorph/store/badger/badger_test.go#L194-L198

If processedAt date of a block has not been found, do not return an error

---

go.mod
go.sum

When BUMPs are being created, it was encoding the whole tree for every transaction. This small update ensures that only the relevant hashes are stored and the BUMP format returned is minimal. This should Massively improve performance issues associated with large memory usage.

fix: update go-bc solves BUMP related memory exhaustion

---

background_worker/jobs/clear_block_transactions_map.go
background_worker/jobs/clear_blocks.go
background_worker/jobs/clear_transactions.go

- Currently duration is formatted in nano seconds `"duration":1665167`
- Use more human readable format

Format time duration as string

---

api/transactionHandler/metamorph.go
metamorph/server.go
metamorph/server_test.go

- Remove direct dependency of API to blocktx
- Get transaction Merkle path in Metamorph, not in api

Get transaction Merkle path in Metamorph, not in api

---

doc/errors.md
validator/default/default_validator.go

Change min tx size in bytes

---

metamorph/processor_response_map.go
metamorph/processor_response_map_test.go
metamorph/processor_test.go

- Do not check for expiry when getting hash from processor response map
- Expiry duration is needed only when cleaning processor response map

Do not check for expiry when getting hash from memory

---

metamorph/server.go

- If Merkle path not found for unmined tx, it is not an error
- Add more info to log

If Merkle path not found for unmined tx, it is not an error

---

blocktx/store/postgresql/postgres_test.go
cmd/metamorph.go
metamorph/mocks/processor_mock.go
metamorph/mocks/store_mock.go
metamorph/processor.go
metamorph/processor_helpers.go
metamorph/processor_options.go
metamorph/processor_response/processor_response.go
metamorph/processor_response/processor_response_test.go
metamorph/processor_response_map.go
metamorph/processor_response_map_test.go
metamorph/processor_test.go
metamorph/server.go
metamorph/store/postgresql/migrations/000011_response_map.down.sql
metamorph/store/postgresql/migrations/000011_response_map.up.sql
metamorph/store/postgresql/postgres.go
metamorph/store/postgresql/postgres_test.go
metamorph/store/store.go
metamorph/types.go

Removed most of stats from code.
Response map doesn't have element after client connection (after ~5 sec)
Getting unmined transactions from database now.
Simplifying some callback hell.

remove objects from map after client connection

---

metamorph/mocks/store_mock.go
metamorph/processor.go
metamorph/processor_test.go
metamorph/store/postgresql/fixtures/metamorph.transactions.yaml
metamorph/store/postgresql/postgres.go
metamorph/store/postgresql/postgres_test.go
metamorph/store/store.go

As multiple metamorph instances can get the INV message, each of them will attempt to update the tx status to SEEN_ON_NETWORK. That can lead to update deadlocks. Therefore only those records should be update which are locked by it's instance.
- Bulk update only those rows which are locked by that metamorph instance
- Set locked only those which have been inserted since a time stamp

fix metamorph updates

---

internal/metamorph/store/postgresql/fixtures/metamorph.transactions.yaml
internal/metamorph/store/postgresql/postgres.go
internal/metamorph/store/postgresql/postgres_test.go

Do not update status in function UpdateStatusBulk if status is SEEN_ON_NETWORK or MINED

fix bulk update status

---

internal/metamorph/store/postgresql/postgres.go

Instead of locking the whole table, lock modified rows in order to avoid deadlock.

lock rows in order to avoid deadlock

---

internal/metamorph/processor.go

p.pm.AnnounceTransaction returns the array of peers to which the transaction was announced, we don't check if the array is empty or not and simply mark it in database that it was announce. Fixed that

Check announcement status

---

internal/beef/beef.go
internal/beef/beef_test.go
internal/beef/bump_validation_test.go
internal/validator/default/default_validator_test.go
pkg/api/handler/default.go
pkg/api/handler/default_test.go
pkg/api/handler/helpers.go
test/beef_test.go
test/endpoint_test.go
test/utils.go

When sending BEEF to Arc with unmined ancestors of a transaction, ARC will return a status of the last transaction in BEEF, but will submit and register callbacks for all unmined transactions in BEEF.

feat(ARCO-139): submit unmined parent txs in beef with callbacks

---

pkg/api/handler/default.go
pkg/api/handler/default_test.go
pkg/api/handler/helpers.go
pkg/api/handler/helpers_test.go
pkg/api/handler/parsers.go

- unify single and batch transaction processing endpoints by removing redundant processing functions.
- fix several errors caused by previously repeated code.
- fix unit tests.
**NOTE:** Due to unification, there is one change in behavior (as noted in unit tests: `default_test.go:359`): in the case of a non-empty JSON without required fields, the system no longer returns `EOF` in the error response. Instead, it returns `error parsing transaction from request: no transaction found - empty request body`.

ARCO-155: (PART 2) unify POST transaction(s) endpoints logic

---

cmd/arc/services/metamorph.go
config/utils.go
config/utils_test.go

It is not an error if no zmq port is available

It is not an error if no zmq port is available

---

cmd/broadcaster-cli/app/keyset/balance/balance.go
cmd/broadcaster-cli/app/keyset/topup/topup.go
cmd/broadcaster-cli/app/keyset/utxos/utxos.go
cmd/broadcaster-cli/app/utxos/broadcast/broadcast.go
cmd/broadcaster-cli/app/utxos/consolidate/consolidate.go
cmd/broadcaster-cli/app/utxos/create/create.go
config/config.go
config/example_config.yaml
internal/broadcaster/broadcaster.go
internal/broadcaster/rate_broadcaster.go
internal/broadcaster/utxo_consolidator.go
internal/broadcaster/utxo_creator.go
internal/woc_client/woc_client.go
internal/woc_client/woc_client_test.go
pkg/api/handler/default.go
pkg/api/handler/tx_finder.go
pkg/keyset/key_set.go

- use only the WoC client throughout the entire codebase to communicate with WoC.
- simplify the interface.
- add tests.

ARCO-147: Refactor WoC client

---

internal/metamorph/response_processor.go
internal/metamorph/response_processor_test.go
internal/metamorph/store/postgresql/migrations/000017_competing_txs_default.down.sql
internal/metamorph/store/postgresql/migrations/000017_competing_txs_default.up.sql
internal/metamorph/store/postgresql/postgres.go
internal/metamorph/store/postgresql/postgres_helpers.go
internal/metamorph/store/postgresql/postgres_test.go

1. Switch from `map` to `sync.Map` in `ResponseProcessor` to avoid accidental race conditions.
2. Better handling of null and empty string values when retrieving `competing_txs` from database.

feat(ARCO-169): refactor ResponseProcessor and competingTxs string to NullString

---

internal/metamorph/mocks/processor_mock.go
internal/metamorph/processor.go
internal/metamorph/processor_helpers.go
internal/metamorph/processor_test.go
internal/metamorph/response_processor.go
internal/metamorph/response_processor_test.go
internal/metamorph/server.go
internal/metamorph/server_test.go
internal/metamorph/types.go

This PR introduces context to transaction processing in metamorph.
This helps to:
- avoid a situation in which a status is still being sent to the channel, even tho a response was sent to the user and nothing is consuming from this channel anymroe
- avoid blocking when the channel is unconsumed and its capacity full

Transaction processing micro optimisation

---

go.mod
internal/metamorph/callbacker.go
internal/tracing/init.go

- Upgrade open telemetry schema to v1.26.0
- Only send callback if there is a callback URL

Upgrade otel schema

---

cmd/arc/services/blocktx.go
cmd/arc/services/metamorph.go
internal/blocktx/processor.go
test/config/bitcoin.conf
test/submit_double_spending_test.go
test/submit_single_test.go

Fix e2e tests.
1. fixing misleading logs in `blocktx` and `metamorph` services that lead to confusion during analysis. The logs are now more precise and readable
eg.:
vs.
2. standardizing logs in the `blocktx` service
3. resolved an issue with incorrect transaction statuses in tests, which was caused by the `metamorph` services being banned by the test nodes:
4. fixing sporadic hazard behavior issues in tests that sometimes caused unpredictable behavior in e2e tests. The tests should now run more stably and deterministically

fix: fix e2e tests

---

test/submit_single_test.go
test/utils.go

Added e2e test for SkipScriptValidation
ARCO-53

ARCO-53: add test for SkipScriptValidation

---

go.mod
internal/blocktx/store/postgresql/postgres_test.go
internal/callbacker/store/postgresql/postgres_test.go
internal/message_queue/nats/client/nats_core/integration_test/client_integration_test.go
internal/message_queue/nats/client/nats_jetstream/integration_test/client_integration_test.go
internal/message_queue/nats/nats_connection/nats_connection_test.go
internal/metamorph/integration_test/double_spend_integration_test.go
internal/metamorph/integration_test/helpers.go
internal/metamorph/store/postgresql/postgres_test.go
internal/test_utils/docker.go
internal/test_utils/utils.go

* move docker related code to test/utils
* move common test functions to test/utils
* decorate test helper functions with `t.Helper()` for better logs
* ensure all docker resources are removed after tests even on errors
ARCO-198

ARCO-198: refactor integration tests

---

CHANGELOG.md
cmd/arc/services/callbacker.go
config/config.go
config/defaults.go
config/example_config.yaml
doc/README.md
internal/callbacker/background_workers.go
internal/callbacker/callbacker.go
internal/callbacker/callbacker_mock.go
internal/callbacker/dispatcher.go
internal/callbacker/dispatcher_test.go
internal/callbacker/quarantine_policy.go
internal/callbacker/quarantine_policy_test.go
internal/callbacker/send_manager.go
internal/callbacker/send_manager_test.go
internal/callbacker/sender.go
internal/callbacker/stats_collector.go
internal/callbacker/store/mocks/store_mock.go
internal/callbacker/store/postgresql/fixtures/delete_failed_older_than/callbacker.callbacks.yaml
internal/callbacker/store/postgresql/fixtures/pop_failed_many/callbacker.callbacks.yaml
internal/callbacker/store/postgresql/internal/tests/utils.go
internal/callbacker/store/postgresql/migrations/000002_add_postponed_until.down.sql
internal/callbacker/store/postgresql/migrations/000002_add_postponed_until.up.sql
internal/callbacker/store/postgresql/migrations/000002_add_quarantine_ts.down.sql
internal/callbacker/store/postgresql/migrations/000002_add_quarantine_ts.up.sql
internal/callbacker/store/postgresql/postgres.go
internal/callbacker/store/postgresql/postgres_test.go
internal/callbacker/store/store.go
test/submit_beef_test.go

This update introduces a quarantine mechanism for receivers that fail to handle callbacks, helping to prevent repeated failed sends.
Changes:
* if a callback fails to send, the receiver is placed in quarantine
* during the quarantine period, all incoming callbacks for that receiver are persisted to storage
* the system periodically checks the stored callbacks and attempts to resend them once the quarantine period ends
* a cleanup process periodically prunes the store, removing outdated and unsent callbacks

ARCO-183: implement quarantine for problematic callback receivers

---

doc/README.md
doc/api.md
doc/arc.json
internal/callbacker/store/postgresql/postgres_test.go
internal/woc_client/woc_client.go
internal/woc_client/woc_client_test.go
pkg/api/arc.json
pkg/api/arc.yaml

- Add callback object specification with examples to `arc.yaml`
- Reference this specification in `README.md`
- Unrelated change: Use `httptest` for test of WoC client `TopUp` function as the previous test failed repeatedly

Callback object documentation

---

internal/metamorph/processor.go
internal/woc_client/woc_client.go

Fix few logs

---

cmd/arc/services/metamorph.go
config/config.go
config/defaults.go
config/example_config.yaml

Allow unseen transactions rebroadcasting interval to be set in config

Unseen transactions rebroadcasting interval setting

---

internal/metamorph/store/postgresql/postgres.go
internal/metamorph/store/postgresql/postgres_test.go

Limit db deadlocks in metamorph

ARCO-123: limit metamorph dead locks

---

internal/blocktx/processor_test.go
pkg/metamorph/client.go
pkg/metamorph/client_test.go

I'm introducing retry policy. I didn't quite like [the idea of submitting the transaction with message queue and implementing that specific logic in case of error ](https://taaltech.atlassian.net/browse/BPAAS-1649)for the following reasons:
1. Submitting TX to message queue doesn't actually do anything different except it retries processing the request after some time (maybe immediately)
2. implementing the the same logic (checking if we have targeted status or request expired) sounds redundant while we have that logic already in `processTransaction`
In this current implementation I do exactly what message queue would do and even more. If we have successful response we return it immediately. If not, we will retry processing request until the timeout expires or we get non-nil response. On …

BPAAS-1649: add retry type of policy

---

config/defaults.go
config/example_config.yaml
internal/metamorph/processor.go
internal/metamorph/processor_helpers.go

Temporarily bypass cache store

Temporarily bypass cache store

---

internal/callbacker/sender_test.go

Adding unit test for callerback sender

test(ARCO-202): Unit test for callbacker sender

---

README.md
config/example_config.yaml
test/config/config.yaml

Documentation for dual-stack capability

docs: dual stack

---

pkg/metamorph/client.go
pkg/metamorph/client_test.go

- If put transaction gets context deadline exceeded, check for status first to avoid false negatives
- Add unit tests

fix: If put transaction returns context deadline exceeded, check for status first to avoid false negatives

---

cmd/arc/services/metamorph.go
config/config.go
config/defaults.go
config/example_config.yaml
internal/metamorph/processor_options.go
internal/metamorph/stats_collector.go
internal/metamorph/store/postgresql/postgres.go
internal/metamorph/store/postgresql/postgres_test.go
internal/metamorph/store/store.go
test/config/config.yaml

- Replace `not mined` metric by `not final` metric as rejected is also a final status
- Exclude `SEEN_IN_ORPHAN_MEMPOOL` from not seen metric

refactor: Fix custom tx status metrics

---

cmd/arc/services/api.go
cmd/arc/services/blocktx.go
cmd/arc/services/metamorph.go
internal/metamorph/processor.go
internal/metamorph/server.go
internal/node_client/node_client.go
internal/node_client/node_client_test.go
internal/validator/default/helpers.go
pkg/metamorph/client.go

- Include only unmined parents in mempool ancestors
- Add hostname to trace attributes
- Add tx id to submit transaction trace
- Move status updated log

fix: get unmined ancestors

---

pkg/api/handler/default.go

Remove additional timeout context which could lead to context deadline exceeded errors

fix(ARCO-294): Remove additional timeout context

---

internal/blocktx/store/postgresql/postgres_test.go
internal/blocktx/store/postgresql/upsert_block_transactions.go

We don't need to insert the transaction with the same txid and blockid as the pair must be unique. No need to update merkle path either as it shouldn't change. 

fix(ARCO-293): Fix conflict on mined transaction insert

---

internal/metamorph/processor.go

Announce an expired transaction first before requesting it

fix: Announce an expired transaction first before requesting it

---

internal/blocktx/processor.go
internal/blocktx/stats_collector.go
internal/blocktx/store/mocks/blocktx_store_mock.go
internal/blocktx/store/postgresql/postgres_test.go
internal/blocktx/store/postgresql/stats.go
internal/blocktx/store/store.go

We are adding a new Prometheus custom metric e.g. arc_block_gaps_count
The value of this metric should be the number of block gaps which can be found

feat(ARCO-296): add blocktx stats collector

---

cmd/arc/services/callbacker.go
internal/callbacker/dispatcher.go
internal/callbacker/send_manager.go
internal/callbacker/send_manager_test.go
internal/callbacker/sender.go
internal/callbacker/sender_test.go

- Make entries channels buffered. 
- Store entries on DB in case of full channels
- Rename single letter variables
- Pass send configuration to send manager

fix(ARCO-298): buffered callbacker channels

---

cmd/arc/services/blocktx.go
cmd/arc/services/metamorph.go
config/config.go
config/defaults.go
config/example_config.yaml
internal/logger/logger.go
internal/p2p/peer.go
internal/p2p/peer_options.go
test/config/config.yaml

Add option to provide different log level for peers. Added TRACE level for even more descriptive logs.
Example:
```
blocktx-2     | Dec  6 08:30:25.096 DBG-4 Received peer.network=TestNet peer.address=node2:18333 cmd=AUTHCH
blocktx-2     | Dec  6 08:30:25.096 DBG-4 Received peer.network=TestNet peer.address=node2:18333 cmd=SENDHEADERS
blocktx-2     | Dec  6 08:30:25.096 DBG-4 Received peer.network=TestNet peer.address=node2:18333 cmd=SENDCMPCT
blocktx-2     | Dec  6 08:30:25.096 DBG-4 Received peer.network=TestNet peer.address=node2:18333 cmd=PING
blocktx-2     | Dec  6 08:30:25.096 DBG-4 Sent peer.network=TestNet peer.address=node2:18333 instance=0 cmd=PONG
```
> NOTE: Requires #686 to be merged first
ARCO-295

feat(ARCO-295): new log level in p2p

---

cmd/arc/services/metamorph.go
internal/metamorph/integration_test/double_spend_integration_test.go
internal/metamorph/zmq.go
internal/metamorph/zmq_handler.go
internal/metamorph/zmq_test.go

- Because we're ranging over a channel in a goroutine, in `/internal/metamorph/zmq.go`, we need to close that channel, otherwise it will stay forever open, causing potential memory leaks.
- Added buffer to the zmq channel, although it seems that ZMQ itself will queue some amount of messages and will not drop them even if we're blocking on that channel.

fix: address potential memory leak in zqm

---

config/example_config.yaml
internal/logger/logger.go
internal/metamorph/zmq.go
internal/metamorph/zmq_test.go

- Add custom log level TRACE - partly taken from https://github.com/bitcoin-sv/arc/pull/686
- Use log level TRACE in zmq

refactor: Set log level for zmq hashtx2 topic to TRACE

---

internal/blocktx/processor.go
internal/blocktx/store/postgresql/postgres_test.go
internal/blocktx/store/postgresql/upsert_block_transactions.go
internal/blocktx/store/store.go
internal/test_utils/utils.go

Currently upserting a block in blocktx is rather slow. To it up the function has been adapter and compared in a benchmark test. That test seems to indicate that the new implementation is faster.
Additionally a benchmark test was added to find the optimal batch size. The results don't show a clear winner but it seems that the best batch size is slightly higher. So that has been increased slightly.

fix(ARCO-311): Speed upsert block transactions

---

internal/callbacker/background_workers_test.go
internal/callbacker/callbacker.go
internal/callbacker/dispatcher_test.go
internal/callbacker/mocks/callbacker_mock.go
internal/callbacker/send_manager.go
internal/callbacker/send_manager_test.go
internal/callbacker/sender.go
internal/callbacker/sender_test.go
internal/callbacker/server_test.go

Currently callbacks with non-existing hosts are still retried even though they should be dropped
- Sender returns two booleans indicating whether the callback was successful and whether it should be retired
- If a host is non-existent, the callback was not successful, but it should not be retried

fix: Drop callbacks with nonexisting host

---

internal/metamorph/processor.go
internal/metamorph/processor_helpers.go
internal/metamorph/processor_test.go

- Metamorph service publishes callbacks on message queue instead of sending them through grpc server to callbacker

refactor: Metamorph processor uses message queue client subscribed to callback topic

---

test/utils.go

Shutdown callback server before closing channels so that writhing to closed channel is not possible

fix: Shutdown callback server before closing channels

---

internal/k8s_watcher/watcher_test.go
internal/logger/logger.go
internal/logger/logger_test.go

fix: Recover time label in logs

---

go.mod
go.sum
internal/api/handler/default.go

- Upgrade echo
- Remove logic to calculate txs sizes as they are not used

fix: rm sizings

---

.github/pull_request_template.md
.github/workflows/go.yaml
cmd/arc/services/blocktx.go
internal/api/handler/default.go
internal/blocktx/processor.go
internal/blocktx/processor_opts.go
internal/blocktx/processor_test.go
internal/message_queue/nats/client/nats_core/nats_core_client.go
internal/metamorph/processor.go
internal/validator/default/default_validator.go
internal/validator/default/default_validator_test.go

- Changed Github Go workflow so that it is executed on commits to any branch in a PR
- Adapt template to our usage
- Small log and comment fixes

refactor: workflows

---

doc/README.md
doc/api.md
internal/api/handler/default.go
internal/metamorph/client.go
pkg/api/arc.go
pkg/api/arc.yaml

Now if the header is set we don't check if tx is present in the db or not to skip its validation. We just go ahead and validate it regardless.

feat(ARCO-320): force validation

---

doc/README.md

[Link to mermaid live editor session](https://mermaid.live/edit#pako:eNptVNty2jAQ_ZUdPYEn9AN4aAcCISTcWvPS2pmJYq9tTWzJI8mhGci_dy3ZQCblCa_2nD17dqUjS1SKbMyyUh2SgmsL-1ksgX6TaCkTVQmZg8QDvJQqeQWNCYo3TCHTqoIaUZsnGI2-w_Q4dQm81MjTdxASZtMfH55q2qacfqM5QTgYhPvtbji8PtlsT3BL5QxSfV_IKsI_-aRbV2EWxex5YozIJRjLbWPaJFvglbwXbkibksCh1vgmFCW5k28QeogwdIygsrHnHsFqu1nMw33_Ge4nqzkMMqVfh31s-2t3P9nMZ88x6yTNnKT5MTwImxRdDV-CevY5c5dzF_XoDnrnwstogRaUrgsuSbIjMJCqg2y7kkqO_BlwmaCxSnfopUM_kBeTJMH6K4WQnSs0TRqCyrxFXwlhILL_xvGvMNYMz70-uJKPVHKHmnypHKOxWJuevvOQxHT-JTSIG0ixRpm2G0QjORSCnPKqDtw4XFfaD4-7hqgTaqDVxuX7RcSjE_Ez2jUvpTAFrJfkKFjNpeGJFUq6bajQ8qolffo8hPvIyeq47l1s1e7TrapqrtGJCQIn7kCTN0HQt0arVvZmcpm6WKlkTl756GUpVo53fQyvIAV1mtOVsKjhTN_fi7W_F_PwBJtWTe9vEGhUOg-CC_fGcW-jNdevnV_uCn6RA1TwutmtA-6ugOaC_NSc6cfYIXfecv9x7eYi-py48InshlWoKy5 …

feat(ARCO-301): simplified reorg diagram

---

cmd/arc/services/blocktx.go
cmd/arc/services/metamorph.go
internal/blocktx/integration_test/helpers.go
internal/blocktx/integration_test/merkle_paths_test.go
internal/blocktx/mq_client.go
internal/blocktx/processor.go
internal/blocktx/processor_opts.go
internal/blocktx/processor_test.go
internal/metamorph/mq_client.go
internal/metamorph/processor.go

- Publish txs seen on network on register-tx topic instead of request-tx topic
- Those txs which have not been registered for example due to a message queue outage will additionally be re-registered in the process so that Merkle path will be calculated for them

fix: re-register txs

---

Makefile
cmd/mcast/node_sidecar/Dockerfile
cmd/mcast/node_sidecar/main.go
docker-compose-mcast.yaml
internal/blocktx/bcnet/mcast/listener.go
internal/metamorph/bcnet/mcast/multicaster.go
internal/multicast/group.go
internal/multicast/mocks/message_handler_mock.go
internal/multicast/tests/group_test.go
test/config/config_mcast.yaml
test/init_test.go
test/submit_02_batch_test.go
test/utils.go

Rebased version of https://github.com/bitcoin-sv/arc/pull/735
E2E Tests for Multicast-Based  Communication
This pull request adds the capability to run end-to-end (E2E) tests using a new communication method with the blockchain, which leverages multicast groups. 
- **Sidecar App**  
Implemented a sidecar application that serves as a bridge between P2P node communication and multicast groups (source `cmd\mcast\node_sidecar)`.
- **Docker-Compose Integration**  
Added a new `docker-compose-mcast.yaml` file to facilitate the test environment setup.
- **Makefile Command**  
Introduced a new command to execute the tests:  
```bash
make run_e2e_mcast_tests
- **IPv6 Configuration Requirement**
Users must ensure Docker is configured to support IPv6 networking for proper test execution.
| Note: …
```

test: multicast

---

README.md
cmd/arc/main.go
cmd/arc/services/api.go
cmd/arc/services/blocktx.go
cmd/arc/services/callbacker.go
cmd/arc/services/metamorph.go
internal/blocktx/processor.go
internal/metamorph/processor.go
pkg/message_queue/nats/client/nats_core/integration_test/client_integration_test.go
pkg/message_queue/nats/client/nats_jetstream/integration_test/client_integration_test.go
pkg/message_queue/nats/nats_connection/nats_connection.go
pkg/message_queue/nats/nats_connection/nats_connection_test.go

- If NATS client connection is closed, shutdown ARC
- Modify NATS connection options settings

fix(ARCO-299): nats reconnect

---

test/submit_01_single_test.go
test/submit_05_reorg_test.go
test/utils.go

- Expand e2e test for block reorg: Check for 2nd callback with updated block hash & merkle path
- Refactor functions used in e2e tests

test: reorg support e2e tests

---

internal/broadcaster/helpers.go
internal/broadcaster/helpers_test.go
internal/broadcaster/rate_broadcaster.go

- NewDynamicTicker returns a dynamic ticker based on time.Ticker. The time intervals linearly decrease starting from startInterval to endInterval. After a specified number of steps the time interval is equal to endInterval.
- Use dynamic ticker in broadcaster-cli so that transactions submitted slowly ramp up instead of starting with a constant rate until the end.

feat: broadcaster ramp up

---

.github/workflows/e2e.yaml
Makefile
cmd/arc/services/metamorph.go
docker-compose.yaml
internal/metamorph/bcnet/mediator.go
internal/metamorph/client.go
internal/metamorph/metamorph_api/metamorph_api.pb.go
internal/metamorph/metamorph_api/metamorph_api.proto
internal/metamorph/metamorph_api/metamorph_api_grpc.pb.go
internal/metamorph/mocks/metamorph_api_mock.go
internal/metamorph/server.go
test/config/config.yaml
test/config/config_mcast.yaml

Fixes
- Do not create new context but use existing one in order not to break the trace
- Make target for running e2e tests with Jaeger
Other changes
- Remove deprecated server functions
- Add traces back to mediator
- Upgrade jaegertracing docker image
- Run e2e tests with 2 blocktx instances
- Remove node 3 from e2e tests => run it with 2 nodes

fix(BPAAS-2065): traces

---

cmd/broadcaster-cli/app/keyset/new/new.go
internal/metamorph/processor.go
internal/metamorph/processor_test.go
internal/metamorph/store/mocks/store_mock.go
internal/metamorph/store/postgresql/fixtures/update_double_spend/metamorph.transactions.yaml
internal/metamorph/store/postgresql/fixtures/update_mined_double_spend_attempted/metamorph.transactions.yaml
internal/metamorph/store/postgresql/postgres.go
internal/metamorph/store/postgresql/postgres_helpers.go
internal/metamorph/store/postgresql/postgres_test.go
internal/metamorph/store/store.go
test/submit_01_single_test.go
test/submit_03_double_spending_test.go
test/utils.go

- Update mined and competing txs in separate db transactions
- Check callbacks in double spend e2e test
- Fix update double spend query to include the current status in the status history
- Rename bulk-update db functions as they're all bulk-update functions

fix: update mined competing

---

internal/blocktx/store/postgresql/insert_block_transactions.go
internal/blocktx/store/postgresql/postgres.go

Create new connection when inserting block transactions

fix: create new connection when inserting block transactions

---

config/defaults.go
config/example_config.yaml
test/config/config.yaml
test/config/config_mcast.yaml

fix: remove default zmq port

---

cmd/arc/main.go
cmd/arc/services/blocktx.go

It repeatedly happened that ARC was not starting when just one of multiple nodes were not available.
In this case ARC should skip the unavailable nodes and connect to the available ones
- Skip peers which cannot be connected to but add remaining peers
- Move log after signal is actually received

fix: node connection

---

internal/callbacker/processor.go

Reduce default store and send intervals

fix(BPAAS-2310): reduce default store and send intervals
