bitcoin-sv/arc

README.md
This probably means we have to update all of the library references too.
=> Update links to new org bitcoin-sv

metamorph/processor_response/ProcessorResponse.go
Fix data race for updating status
=> Fix response race

api/handler/default.go
- add error logs in api default handler
=> BPAAS-935: add error logs in api default handler

broadcaster/broadcaster.go, cmd/broadcaster/main.go
- Add flag for using broadcaster on testnet
- Add additional logging to broadcaster
=> Add testnet flag. Add additional logging

api/transactionHandler/bitcoin-node.go
Fix the interface match for the bitcoin node
=> add SubmitTransactions to bitcoin node interface

api/test/node.go, metamorph/mock_test.go
Add mock implementation of interface functions
=> add mock implementation of interface functions

README.md, cmd/broadcaster/examples.txt, cmd/broadcaster/main.go, config.yaml
- add descriptions to settings in config file
- update README.md
=> Viper config documentation

doc/README.md
- We moved from `gocore` package to `viper`
- Update documentation
=> Update documentation about settings

api/handler/default.go
- handle error from metamorph to add context to the response
- add additional log
- add status code
=> BPAAS-985: Handle error and add status code, logging in post batch txs api endpoint

api/handler/default.go
- log original error if extend transaction fails
=> BPAAS-1129: Log original error

.github/workflows/image.yml
Add pipeline for building and pushing the OCI image
=> Add pipeline for building and pushing the OCI image

api/handler/default.go, api/handler/default_test.go, api/handler/helpers.go, api/status.go
- Refactor test for `POSTTransaction()` to table based test
- Add test cases to increase coverage
=> POSTTransaction - code coverage

database/migrations/000001_create_blocks.down.sql, database/migrations/000001_create_blocks.up.sql, database/migrations/000002_create_block_transactions_map.down.sql, database/migrations/000002_create_block_transactions_map.up.sql, database/migrations/000003_create_transactions.down.sql, database/migrations/000003_create_transactions.up.sql, database/schema.sql , docker-compose.dev.yml, docker-compose.yml, scripts/install-migrate.sh
- added database migrations and golang migrate library 
- added go migrate library installation script 
- added separate docker compose for local arc and postgres database
=>  Add database migrations

config.yaml, metamorph/processor.go
In accordance with @icellan removing the error log file in metamorph
It is replaced with a simple log entry
=> Remove metamorph error logging to file

metamorph/server.go
Fix for issue: https://github.com/bitcoin-sv/arc/issues/116#issue-1966311281
=> fix: check for nil BlockHash in GetTransaction

callbacker/client.go, callbacker/server.go, callbacker/server_test.go, cmd/callbacker.go, cmd/callbacker/main.go, cmd/metamorph.go, main.go
- add structured logging to callbacker server
- add unit tests
=> Add structured logging to callbacker server

main.go, tracing/init.go, tracing/init_test.go
Add structured logging to main
=> Add structured logging to main.go

cmd/metamorph.go, metamorph/processor.go, metamorph/processor_test.go, metamorph/store.go
No source is needed for metamorph if metamorph is decentralised
=> Do not set a source if metamorph is decentralised

blocktx/store/sql/register_transaction.go
The query couldn't parse the result in chainhash.Hash structure and required []byte. The error was always ignored and this line never worked. Because of that block hash was empty which determined further logic change.
=> BPAAS-1150-fix-sql-result-parsing

.github/workflows/go.yml, test/config/config.yaml
- Do not show output from nodes in e2e job
- Show only test output and arc output with log level INFO
=> Show only output from arc & e2e tests in pipeline

background_jobs/jobs/clear_blocks_test.go
Set increasing height. Random height which is equal will violate the unique height index
=> Fix flaky test

sonar-project.properties
Exclude all files in a sub dir of tests folder from code coverage calculation
=> Exclude tests folder from Sonar cloud coverage calculation

blocktx/peer_handler.go, blocktx/store/sql/insert_block.go, cmd/api.go, metamorph/processor.go, metamorph/store/badger/badger.go, metamorph/store/sql/sql.go
Check errors with `Is` function
=> Check errors with Is function

.github/workflows/static-analysis.yml
- Ensure race conditions are checked during all the testing scenarios
=> Enable race condiition check during static analysis tests

metamorph/processor.go, metamorph/server.go
=> Add debug logs

metamorph/store/dynamodb/dynamodb.go, metamorph/store/dynamodb/dynamodb_test.go
- update the `mined_at` field when updating the status to `MINED`
=> Update mined has to update the 'mined_at' field

main.go
- Check if k8s-watcher flag is passed, so that k8s-watcher can be started individually
=> BAARC-44: check is flag passed

cmd/k8s_watcher.go, k8s_watcher/watcher.go
- Add more context to errors
- Add debug logs
=> Add context to err messages

cmd/background_worker.go
=> Fix settings strings

cmd/metamorph.go, test/config/config.yaml
- Return error if setting for data record retention days is not found
=> Return error if setting for data record retention days is not found

cmd/metamorph.go, config.yaml, test/config/config.yaml
- Only try to find the fixed IP address in metamorph is configured in the settings
=> Fix metamorph source

blocktx/peer_handler.go, blocktx/peer_handler_test.go
- fix wrong error comparison
- add logs
=> BAARC-86: Change not found error. Add more logs

blocktx/block_notifier_test.go, blocktx/peer_handler.go, blocktx/peer_handler_test.go
- Only fill gaps if primary
- Update unit tests
=> Only fill gaps if primary

blocktx/peer_handler.go, blocktx/store/sql/insert_block_transactions.go
- Add more context to errors in peer handler
=> Add context to errors in peer handler

cmd/metamorph.go, config.yaml, metamorph/server.go
- Do not respond with error if transaction initialization with blocktx fails or times out
- Make blocktx timeout duration configurable
=> decouple metamorph from blocktx

README.md
- add documentation on how to access the profiler
=> Profiler documentation

database/migrations/metamorph/postgres/000005_status_locked_by_index.down.sql, database/migrations/metamorph/postgres/000005_status_locked_by_index.up.sql
- multi-column index for locked_by and status
=> multi-column index for locked_by and status

metamorph/store/postgresql/postgres.go, test/docker-compose.yml
=> Load maximum 20k unlocked records at the time

metamorph/store/postgresql/postgres.go, metamorph/store/postgresql/postgres_test.go
- Skip update of intermediate statuses in postgres implementation
=> Skip update of intermediate statuses

broadcaster/broadcaster.go, config.yaml, metamorph/processor.go
- Change min mining fee
- Add log in metamorph when hash gets announced
=> Broadcaster min fee

metamorph/store/postgresql/postgres.go
=> Return response object

metamorph/callbacker.go, metamorph/processor.go
- Add more information to callback logs
=> Add more information to callback logs

test/endpoint_test.go
Test added for skipfee vlaidation
=>  adding test for skipfeevalidation

metamorph/server.go
- Compare error strings instead of errors
=> Compare error strings instead of errors

blocktx/interface.go, blocktx/server.go, metamorph/server.go, metamorph/server_test.go
- Change error message and var name
=> Change error message and var name

test/endpoint_test.go
Adding test for skip tx validation
The test passed while running locally
Sending a transaction with low fees skip tx validation flag allows it to submit the transaction.
=>  adding test for skiptx validation

blocktx/store/sql/sql.go, blocktx/store/sql/try_to_become_primary.go
log db string without password
=> log db string without password

blocktx/health_check.go, blocktx/peer_handler.go, blocktx/server.go, blocktx/server_test.go, cmd/blocktx.go
=> add health check

blocktx/async/nats_mq/mq_client.go, blocktx/async/nats_mq/mq_client_test.go, cmd/blocktx.go, cmd/metamorph.go, config.yaml, test/config/config.yaml
- Increase buffer size of mined txs channel to theoretical maximum
=> Increase buffer size of mined txs channel to theoretical maximum

main.go, test/config/config.yaml
make prometheus server non-blocking
=> Fix prometheus server

test/endpoint_test.go
=>  clean up work

metamorph/processor.go, metamorph/processor_helpers.go, metamorph/processor_response/processor_response.go, metamorph/processor_response/processor_response_test.go
- Reduce the size of processor response, in order to save memory per transaction
=> Reduce size of processor response

api/handler/default.go, broadcaster/api.go, broadcaster/broadcaster.go, broadcaster/dry_run.go, broadcaster/metamorph.go, broadcaster/mocks/arc_client_mock.go, broadcaster/rate_broadcaster.go, broadcaster/rate_broadcaster_test.go, cmd/broadcaster-cli/app/keyset/dist/dist.go, cmd/broadcaster-cli/app/root.go, cmd/broadcaster-cli/app/utxos/broadcast/broadcast.go, config.yaml, lib/woc_client/woc_client.go
- Add full status updates flag to broadcaster-cli
=> Add full status updates flag

doc/README.md
Complete transaction life cycle diagram
=> Complete transaction life cycle diagram

cmd/broadcaster-cli/app/keyset/balance/balance.go, cmd/broadcaster-cli/app/keyset/topup/topup.go, cmd/broadcaster-cli/app/utxos/broadcast/broadcast.go, cmd/broadcaster-cli/app/utxos/consolidate/consolidate.go, cmd/broadcaster-cli/app/utxos/create/create.go, cmd/broadcaster-cli/app/utxos/dist/dist.go, internal/broadcaster/mocks/utxo_client_mock.go, internal/broadcaster/rate_broadcaster.go, internal/woc_client/woc_client.go
- WoC client functions with retries
=> WoC client has functions with retries

cmd/arc/services/blocktx.go, internal/blocktx/async/nats_mq/mq_client.go, internal/blocktx/async/nats_mq/mq_client_test.go, internal/blocktx/mq_client.go, internal/blocktx/mq_mock.go, internal/blocktx/peer_handler.go, internal/blocktx/store/blocktx_store_mock.go, internal/blocktx/store/interface.go, internal/blocktx/store/postgresql/get_transaction.go, internal/blocktx/store/postgresql/postgres_test.go, internal/metamorph/async/nats_mq/client.go, internal/metamorph/mocks/message_queue_mock.go, internal/metamorph/mq_client.go, internal/metamorph/processor.go, internal/metamorph/processor_test.go
We need to somehow check if transaction has mined status in case it has SEEN_ON_NETWORK for too long.
=> implement requesting stalled transactions

internal/metamorph/processor.go
Log only if there were seen on network txs to be requested
=> Log only if there were seen on network txs to be requested

sonar-project.properties
- Update arc.go path
- Rm old paths
=> Update sonar exclusions

internal/metamorph/callbacker.go
- Log debug if callback fails
- Only log warning after all retries failed
=> Reduce amount of callback logs

internal/blocktx/server.go, internal/grpc_opts/grpc_opts.go, internal/metamorph/server.go
Register panics counter with different names in blocktx and metamorph
=> Register panics counter with different names in blocktx and metamorph

cmd/arc/services/metamorph.go, config/config.yaml, deployments/config/config.yaml, internal/metamorph/processor_options.go, internal/metamorph/stats_collector.go, test/config/config.yaml
- Stat time limits are configurable
=> Stat time limits are configurable

internal/metamorph/callbacker.go, internal/metamorph/mocks/callback_sender_mock.go, internal/metamorph/processor.go, internal/metamorph/processor_test.go
Maybe using mutex and disposed guard is a little over engineering, I'm waiting for comments
=> ARCO-70: graceful shutdown callbacker

cmd/arc/services/blocktx.go, config/config.yaml, internal/blocktx/peer_handler.go, test/config/config.yaml
- Fill gaps interval is configurable setting
=> Fill gaps interval is configurable setting

README.md, doc/README.md
=> Deprecate arc-client-js

cmd/arc/services/metamorph.go
- Close database after server shutdown so that unlocking records won't fail: https://github.com/bitcoin-sv/arc/blob/82b2cd1583b97e169d23230303884e1f1f095fbd/internal/metamorph/processor.go#L161
=> Close database after server shutdown

internal/metamorph/processor.go
Don't pass map by reference as it's not really needed because we can clear it easily.
=> clear map properly

doc/README.md
- Update state diagram => Add state transition from SEEN_IN_ORPHAN_MEMPOOL to ACCEPTED_BY_NETWORK
- Use Mermaid instead of PlantUML
=> Update state diagram. Use Mermaid instead of PlantUML

internal/metamorph/peer_handler.go, internal/metamorph/zmq.go
- Log colliding tx ids and tx hex
=> Log colliding tx ids and tx hex

pkg/api/handler/default.go
- Allow to set callback token without callback URL
=> Allow to set callback token without callback URL

internal/metamorph/stats_collector.go, internal/metamorph/store/postgresql/postgres.go, internal/metamorph/store/postgresql/postgres_test.go, internal/metamorph/store/store.go
Get total mined and seen on network
=> Get total mined and seen on network

go.mod, internal/grpc_opts/grpc_opts.go
Remove gprc retries as it can lead to false negatives
=> Remove gprc retries

internal/metamorph/store/postgresql/postgres.go, internal/metamorph/store/postgresql/postgres_test.go
Set all records unlocked by name
=> Set all records unlocked by name

cmd/broadcaster-cli/app/keyset/address/address.go, cmd/broadcaster-cli/app/keyset/balance/balance.go, cmd/broadcaster-cli/app/keyset/topup/topup.go, cmd/broadcaster-cli/app/keyset/utxos/utxos.go, cmd/broadcaster-cli/helper/functions.go
updating keyset utxos
updating helper function within broadcaster cli
=>  updating helper functions and updating utxos

internal/metamorph/processor.go, internal/metamorph/processor_test.go
Request and announce transaction initially when submitting single transactions
=> request-announce

cmd/broadcaster-cli/app/utxos/broadcast/broadcast.go, cmd/broadcaster-cli/app/utxos/consolidate/consolidate.go, cmd/broadcaster-cli/app/utxos/create/create.go
Refactor for UTXOS
1) Create
2) consolidate
3) broadcast
=>  refactor for broadcast functions

go.mod, go.sum
=> Upgrade go p2p

internal/metamorph/processor.go, internal/metamorph/store/postgresql/postgres.go, internal/metamorph/store/postgresql/postgres_test.go, test/submit_single_test.go, test/utils.go
- Add new callback to tx when submitting already existing one
=> ARCO-150: submit existing tx with new callback

CHANGELOG.md
- Added info about multiple callbacks to single tx in changelog
=> ARCO-150: update changelog

cmd/arc/services/api.go
- Use slog logger for echo logging
=> Use slog logger for echo logging

internal/broadcaster/broadcaster_test.go, internal/broadcaster/multi_rate_broadcaster_test.go, internal/broadcaster/rate_broadcaster.go, internal/broadcaster/rate_broadcaster_test.go
Added test coverage for rate broadcaster `Start()` function
=> Test coverage for rate broadcaster

config/load.go, config/load_test.go, config/utils.go, config/utils_test.go, internal/beef/beef.go, internal/beef/beef_test.go, internal/beef/bump.go, internal/beef/bump_test.go, internal/fees/fees_test.go, internal/logger/logger.go, internal/logger/logger_test.go, internal/message_queue/nats/nats_connection/nats_connection.go, internal/message_queue/nats/nats_connection/nats_connection_test.go, internal/woc_client/woc_client.go, internal/woc_client/woc_client_test.go
First part of refactoring errors and unification unit tests
ARCO-196
=> ARCO-196: refactor errors and unify unit tests

CHANGELOG.md, cmd/arc/services/callbacker.go, doc/README.md, internal/callbacker/dispatcher.go, internal/callbacker/send_manager.go
=> ARCO-200: document changes and describe callbacker components

internal/blocktx/store/postgresql/get_block_gaps.go, internal/blocktx/store/postgresql/get_mined_transactions.go, internal/blocktx/store/postgresql/postgres.go, internal/blocktx/store/postgresql/register_transactions.go, internal/blocktx/store/postgresql/set_block_processing.go, internal/blocktx/store/postgresql/upsert_block_transactions.go, internal/metamorph/store/postgresql/postgres.go, internal/metamorph/store/postgresql/postgres_helpers.go
=> ARCO-156: correctly release db resources

CHANGELOG.md, doc/README.md, doc/api.md, doc/arc.json
=> ARCO-206: add doc

internal/broadcaster/utxo_creator.go, internal/broadcaster/utxo_creator_test.go
Removed the existing tests and added new test
=> ARCO-153: removing existing test and updating new test

internal/blocktx/processor.go
=> ARCO-220: wait until blocktx is able to process next block

internal/blocktx/processor.go
Add log before sending request for a block
=> Log when sending block request

cmd/arc/services/metamorph.go, internal/blocktx/processor_opts.go, internal/blocktx/store/postgresql/postgres.go, internal/metamorph/grpc_callbacker.go, internal/metamorph/processor_options.go, internal/metamorph/server.go, internal/metamorph/store/postgresql/postgres.go, internal/tracing/helper.go, internal/validator/default/default_validator.go, internal/validator/default/default_validator_test.go, internal/validator/default/helpers.go, internal/validator/default/helpers_test.go, internal/validator/validator.go, pkg/api/handler/default.go, pkg/api/handler/default_test.go, pkg/api/handler/internal/TxFinder/cached_tx_finder.go, pkg/api/handler/internal/TxFinder/cached_tx_finder_test.go, pkg/api/handler/internal/TxFinder/tx_finder.go, pkg/api/status.go, pkg/metamorph/client.go, pkg/metamorph/mocks/transaction_handler_mock.go
- Add more traces & attributes (especially for cumulative fee validation)
`make run_e2e_tests_with_tracing`
=> feat(ARCO-276): Add traces & attributes

internal/blocktx/processor.go, pkg/api/handler/default.go
=> fix(ARCO-276): Fix span names

cmd/arc/services/metamorph.go, internal/metamorph/integration_test/double_spend_integration_test.go, internal/metamorph/zmq.go, internal/metamorph/zmq_handler.go, internal/metamorph/zmq_test.go
The code related to the zmq connection from the `go-bitcoin` library has been refactored and moved to our repository
ARCO-279
=> feat(ARCO-279): add custom zmq listener

README.md, cmd/arc/services/api.go, cmd/arc/services/blocktx.go, cmd/arc/services/metamorph.go, config/config.go, config/defaults.go, config/example_config.yaml, config/test_files/config.yaml, internal/tracing/init.go, test/config/config.yaml
=> test(ARCO-280): Make tracing sampling configurable

.github/workflows/go.yaml, Makefile, docker-compose.yaml, test/config/config.yaml, test/e2e_globals.go
Simplify commands for running e2e tests
run `make run_e2e_tests`
=> refactor: Simplify e2e test commands

internal/callbacker/sender.go, internal/callbacker/sender_test.go
=> refactor(ARCO-284): Refactor callbacker sender #644

pkg/metamorph/client.go
Reduce duplicated code in metamorph client
=> refactor: Reduce duplicated code in metamorph client

internal/node_client/node_client.go, internal/node_client/node_client_test.go, internal/tx_finder/tx_finder.go, internal/validator/default/helpers.go, test/submit_01_single_test.go
Node client not finding ancestors in mempool does not return an error
=> fix: Node client

internal/callbacker/server_test.go
Adding unit test for callbacker server
Closes ARCO-203.
=> test(ARCO-203): Unit test for callbacker server

cmd/arc/services/callbacker.go, config/config.go, config/defaults.go, config/example_config.yaml, go.mod, internal/callbacker/dispatcher.go, internal/callbacker/dispatcher_test.go, internal/callbacker/send_manager.go, internal/callbacker/send_manager_test.go, internal/callbacker/server_test.go
Add configurable callback sending delay to fix some clients issue with too fast callbacks 
=> fix: add delay before actual callback send

internal/callbacker/server_test.go
Fix flaky test
run `make test`
=> test(ARCO-203): Fix flaky test

internal/metamorph/server.go, internal/metamorph/server_test.go
- Check in intervals whether the tx was seen on network & updated on DB by another metamorph instance
run `make test`
=> fix(ARCO-212): Check status interval

pkg/metamorph/client.go
=> fix(ARCO-294): use new context for fallback getting tx status

pkg/metamorph/client.go
=> fix(ARCO-294): handle trace span correctly

internal/blocktx/processor.go, internal/blocktx/store/postgresql/upsert_block_transactions.go, internal/metamorph/server.go
- Fix trace name
- Add attributes
=> fix: Fix trace name & add attributes

internal/callbacker/server_test.go, internal/metamorph/server.go
- Fix trace attribute name, attribute for wait for status
- Fix flaky test
=> fix: Fix trace attribute name, attribute for wait for status

.github/workflows/go.yaml
=> feat: remove unnecessary github actions

internal/p2p/tests/network_messenger_test.go
=> feat: add network messenger unit tests

internal/callbacker/sender.go
Info log for every successful callback
=> refactor: Info log for every successful callback

pkg/metamorph/client.go
Add tx id as attribute to get tx status trace
=> refactor: Add tx id as attribute to get tx status trace

internal/p2p/peer.go
=> fix: p2p.Peer restart

internal/blocktx/processor.go
=> fix: fix nil status when parsing block that's already existing

internal/p2p/peer.go, internal/p2p/tests/peer_test.go
=> fix: p2p unhandled msg

cmd/arc/services/blocktx.go, config/config.go, config/defaults.go, config/example_config.yaml, internal/blocktx/blockchain_communication/p2p/message_handler.go, internal/blocktx/processor.go, internal/blocktx/processor_opts.go
- Allow setting the max block processing duration as a setting
=> refactor: With max block processing duration

cmd/arc/main.go, cmd/arc/services/api.go, cmd/arc/services/blocktx.go, cmd/arc/services/callbacker.go, cmd/arc/services/k8s_watcher.go, cmd/arc/services/metamorph.go, config/config.go, config/defaults.go, config/example_config.yaml, internal/blocktx/processor.go, internal/blocktx/processor_test.go, internal/metamorph/processor.go, internal/metamorph/processor_test.go, test/config/config.yaml
- Start collecting stats in blocktx
- Refactor prometheus configuration
=> fix: Collect stats in blocktx

internal/blocktx/bcnet/blocktx_p2p/message_handler.go, internal/metamorph/bcnet/metamorph_p2p/message_handler.go, internal/p2p/peer.go, internal/p2p/tests/peer_test.go
=> fix: p2p eof 

.github/workflows/image.yaml, internal/blocktx/processor.go
- Add attribute showing the nr of transactions in trace
- Only build image if tag begins with 'v'
=> refactor: Nr of txs trace attribute

cmd/arc/services/blocktx.go, config/config.go, config/defaults.go, config/example_config.yaml, test/config/config.yaml
Have an option to disable filling the gaps in config.
=> feat: make fillGaps configurable

internal/blocktx/store/postgresql/migrations/000021_remove_unique_height_is_longest.down.sql, internal/blocktx/store/postgresql/migrations/000021_remove_unique_height_is_longest.up.sql, internal/blocktx/store/postgresql/postgres_test.go
=> fix: temporarily remove unique index on blocks and height

cmd/arc/services/metamorph.go, config/config.go, config/defaults.go, config/example_config.yaml, internal/metamorph/processor.go, internal/metamorph/processor_options.go, internal/metamorph/stats_collector.go
- Rename name of setting for rechecking txs that are seen on network
- Remove unused metric
=> refactor: Rename setting name

internal/message_queue/nats/client/nats_jetstream/nats_jetstream_client.go
=> fix: Return if mq client is nil

internal/api/handler/default.go
=> fix: timeout header check

internal/api/handler/default.go
Return the status if callback already exists or no callback given
=> fix(ARCO-302): Return the status if callback already exists 

internal/metamorph/processor.go, internal/metamorph/server.go
check for empty callbacks, if so set nil
=> feat(ARCO-330): check for emptiness

internal/cache/in_memory_test.go, internal/cache/redis_test.go, internal/logger/logger.go, internal/logger/logger_test.go, internal/validator/common_validation_test.go
Added tests for the files with lowest coverage so far
=> test(ARCO-332): Coverage review

internal/k8s_watcher/watcher.go
=> fix: remove nil

.github/workflows/static-analysis.yaml, internal/multicast/tests/group_test.go
Run multicast test in pipeline
=> test: commented flaky test

CHANGELOG.md, README.md, doc/README.md, internal/blocktx/processor.go, internal/callbacker/send_manager/send_manager.go, internal/callbacker/sender.go
- Update callbacker documentation
- Change log levels
=> refactor: callbacker logs

internal/grpc_utils/opts.go
Register grpc server metrics in prometheus client so that grpc server metrics are exported
=> fix: grpc server metrics

internal/grpc_utils/opts.go
=> feat(BPAAS-2020): register once

cmd/arc/services/blocktx.go, go.mod, go.sum, internal/blocktx/processor.go, internal/blocktx/processor_test.go, internal/blocktx/stats_collector.go, internal/blocktx/stats_collector_test.go, internal/metamorph/stats_collector.go
- blocktx stats collector separate from processor
- test coverage for stats collector
=> refactor: blocktx stats collector

cmd/arc/services/api.go, go.mod, go.sum, internal/api/handler/default.go, internal/api/handler/default_test.go, internal/api/handler/stats.go, internal/api/handler/stats_test.go
New prometheus metric counting submissions in `api` after successful validation
=> feat: tx submission counter

internal/blocktx/health_check.go, internal/blocktx/health_check_test.go, internal/metamorph/health_check.go, internal/metamorph/health_check_test.go
Remove nats check from metamorph & blocktx health check
=> refactor: Remove nats check from metamorph & blocktx health check

.github/workflows/static-analysis.yaml, .golangci.yml, examples/custom/main.go, examples/customhandler/handler.go, examples/customhandler/main.go, test/utils.go
=> refactor(BPAAS-2034): Upgrade golangci-lint to v2

sonar-project.properties
=> chore: Update sonar exclusions

README.md
Add few basic badges in Readme
=> docs: Badges in readme

.golangci.yml, internal/broadcaster/utxo_splitter.go, internal/metamorph/stats_collector.go
=> refactor: Activate slog-lint linter

.github/workflows/e2e.yaml, .github/workflows/go.yaml, .github/workflows/release.yaml, .github/workflows/static-analysis.yaml
- Split go and e2e workflows
- Start go workflow only if certain files or paths are changed
=> chore: workflows

internal/api/transaction_handler/bitcoin_node_test.go, internal/broadcaster/broadcaster_test.go, internal/broadcaster/multi_rate_broadcaster_test.go, internal/broadcaster/rate_broadcaster_test.go
Changes on broadcaster, rate_broadcaster and bitcoin node increasing the number of scenarios and the cover rate
=> test(BPAAS-2055): coverage on broadcaster rate_broadcaster and bitcoin node

cmd/arc/services/api.go
Add missing headers to api logs
=> fix(BPAAS-2073): Add missing headers to api logs

.golangci.yml, config/config.go, go.mod, go.sum, internal/api/handler/default.go, internal/api/helpers.go, internal/beef/beef.go, internal/blocktx/server.go, internal/blocktx/store/mocks/blocktx_store_mock.go, internal/blocktx/store/postgresql/postgres_test.go, internal/blocktx/store/postgresql/verify_merkle_roots.go, internal/blocktx/store/store.go, internal/broadcaster/utxo_creator.go, internal/callbacker/store/postgresql/postgres.go, internal/callbacker/store/postgresql/postgres_test.go, internal/metamorph/processor_test.go, internal/metamorph/server.go, internal/metamorph/store/postgresql/postgres.go, internal/metamorph/store/postgresql/postgres_helpers.go, internal/p2p/network_messenger.go, internal/p2p/network_messenger_test.go, internal/validator/beef/beef_validator.go, internal/validator/default/default_validator.go, test/submit_04_beef_test.go, test/utils.go
=> feat(BPAAS-2064): add gosec linter

.github/workflows/static-analysis.yaml
=> chore: Update Sonar Qube scan

internal/blocktx/store/postgresql/postgres_test.go
Add test coverage for clear blocktx table
=> test: Add test coverage for clear blocktx table

.github/workflows/sonar-cloud.yaml, .github/workflows/static-analysis.yaml, internal/broadcaster/rate_broadcaster_test.go
Fix rate broadcaster async test which randomly varies coverage
=> test(BPAAS-2076): fix rate broadcaster async test

cmd/arc/main.go, internal/api/handler/default.go, internal/logger/logger.go
Add event id as attribute to trace
=> refactor: event attribute

cmd/arc/services/api.go, internal/node_client/client.go, internal/node_client/node_client.go, internal/node_client/node_client_test.go, internal/node_client/rpc_client.go, internal/node_client/rpc_client_test.go, internal/node_client/test_utils.go, test/submit_05_reorg_test.go
- RPC bitcoin client with context
=> feat(BPAAS-2078): RPC bitcoin client with context

.gitignore, Makefile, cmd/arc/services/api.go, internal/blocktx/processor.go, internal/metamorph/bcnet/metamorph_p2p/message_handler.go, internal/metamorph/processor_test.go
- Ensure writing to registration channel non-blocking
- Update few logs
- Separate Make targets for coverage and tests and for short and full tests
=> refactor: blocktx register ch

internal/blocktx/store/postgresql/migrations/000025_add_indices.down.sql, internal/blocktx/store/postgresql/migrations/000025_add_indices.up.sql
=> refactor: block id index

internal/api/dictionary/dictionary.go, internal/beef/bump.go, internal/blocktx/processor.go, internal/blocktx/store/postgresql/migrations/000021_block_transactions.up.sql, internal/blocktx/store/postgresql/set_block_processing.go, internal/blocktx/store/postgresql/verify_merkle_roots.go, internal/metamorph/store/postgresql/postgres.go, internal/metamorph/zmq_handler.go, pkg/message_queue/nats/client/nats_core/nats_core_client.go, pkg/message_queue/nats/client/nats_jetstream/nats_jetstream_client.go
=> feat(BPAAS-2080): refactor for stylish issues

internal/blocktx/bcnet/init_test.go
Added a new test to trigger the SetExternalHandler method
=> test(BPAAS-2092): Adding test to trigger SetExternalHandler

internal/blocktx/processor.go, internal/broadcaster/rate_broadcaster_test.go, internal/metamorph/processor.go
- Fix flaky unit test `TestRateBroadcasterStartAsync`
- Log each updated orphaned block
=> fix(BPAAS-2094): Fix flaky unit test

internal/metamorph/processor.go, internal/metamorph/processor_test.go
=> fix: Reduce load limit

internal/metamorph/integration_test/processor_integration_test.go, internal/metamorph/processor.go, internal/metamorph/processor_helpers.go, internal/metamorph/processor_helpers_test.go, internal/metamorph/processor_routines.go, internal/metamorph/processor_routines_test.go, internal/metamorph/processor_test.go
- Reuse repetitive code to start a background routine
- Use mediator mock instead of p2p peer manager
=> refactor: mtm processor

internal/blocktx/processor_test.go
Adding options to fully cover processor_opts.go
=> test(BPAAS-2097): Adding options to fully cover processor_opts.go

.golangci.yml, internal/api/handler/parsers.go, internal/api/handler/parsers_test.go, internal/blocktx/processor.go, internal/blocktx/store/postgresql/verify_merkle_roots.go, internal/broadcaster/api.go, internal/broadcaster/rate_broadcaster.go
Reducing complexity of:
- parsers.go 
- blocktx/processor.go
- broadcaster/api.go 
- blocktx/.../verify_merkle_roots.go
=> chore(BPAAS-2118): Reducing complexity based on Sonarcloud feedback

.golangci.yml, internal/broadcaster/rate_broadcaster.go, internal/broadcaster/rate_broadcaster_test.go, internal/broadcaster/utxo_consolidator.go, internal/callbacker/processor.go, internal/metamorph/processor_routines.go, internal/metamorph/store/postgresql/postgres.go
Refactor rate_broadcaster.go and utxo_consolidator.go
=> chore(BPAAS-2118): Reduce complexity

cmd/arc/services/api.go, examples/custom/main.go, examples/customhandler/handler.go, examples/simple/main.go, internal/api/handler/default.go, internal/api/handler/default_test.go, internal/validator/default/default_validator.go, internal/validator/default/default_validator_test.go
=> feat(BPAAS-2138): request block height in intervals

cmd/broadcaster-cli/app/keyset/address/address.go, cmd/broadcaster-cli/app/keyset/balance/balance.go, cmd/broadcaster-cli/app/keyset/keyset.go, cmd/broadcaster-cli/app/keyset/new/new.go, cmd/broadcaster-cli/app/keyset/topup/topup.go, cmd/broadcaster-cli/app/keyset/utxos/utxos.go, cmd/broadcaster-cli/app/root.go, cmd/broadcaster-cli/app/utxos/broadcast/broadcast.go, cmd/broadcaster-cli/app/utxos/consolidate/consolidate.go, cmd/broadcaster-cli/app/utxos/create/create.go, cmd/broadcaster-cli/app/utxos/split/split.go, cmd/broadcaster-cli/app/utxos/utxos.go, cmd/broadcaster-cli/broadcaster-cli-example.yaml, cmd/broadcaster-cli/helper/functions.go, internal/broadcaster/api.go, internal/logger/logger.go
- Setting for log level and log format in broadcaster-cli
- Refactor reading of settings - do not return error
=> feat: broadcaster logs

cmd/broadcaster-cli/app/utxos/broadcast/broadcast.go, cmd/broadcaster-cli/app/utxos/consolidate/consolidate.go, cmd/broadcaster-cli/app/utxos/create/create.go, cmd/broadcaster-cli/app/utxos/split/split.go, cmd/broadcaster-cli/broadcaster-cli-example.yaml, cmd/broadcaster-cli/helper/functions.go, internal/broadcaster/api.go, internal/broadcaster/api_test.go, internal/broadcaster/broadcaster.go, internal/broadcaster/helpers.go, internal/broadcaster/helpers_test.go, internal/broadcaster/multi_rate_broadcaster.go, pkg/woc_client/woc_client.go, pkg/woc_client/woc_client_test.go
- Fix setting locking script in woc client
- Use logger to print errors in arc-client
- Allow switching between constant and ramp up ticker in config
=> fix(BPAAS-2151): Fix WoC client

Dockerfile
Docker file changed to apt-get alphabetically
=> refactor(BPAAS-2178): apt-get alphabetically in Docker file

internal/callbacker/sender.go
=> chore(BPAAS-2279): log callback response

internal/callbacker/processor.go, internal/callbacker/processor_routines.go, internal/callbacker/processor_routines_test.go, internal/callbacker/store/postgresql/fixtures/clear/callbacker.transaction_callbacks.yaml, internal/callbacker/store/postgresql/fixtures/get_unsent/callbacker.transaction_callbacks.yaml, internal/callbacker/store/postgresql/fixtures/insert/callbacker.transaction_callbacks.yaml, internal/callbacker/store/postgresql/fixtures/set_sent/callbacker.transaction_callbacks.yaml, internal/callbacker/store/postgresql/fixtures/unset_pending/callbacker.transaction_callbacks.yaml, internal/callbacker/store/postgresql/migrations/000007_create_functions.down.sql, internal/callbacker/store/postgresql/migrations/000007_create_functions.up.sql, internal/callbacker/store/postgresql/migrations/000008_tx_callbacks_hash.down.sql, internal/callbacker/store/postgresql/migrations/000008_tx_callbacks_hash.up.sql, internal/callbacker/store/postgresql/postgres.go
- Add hash to `callbacker.transaction_callbacks` table with index
=> refactor(BPAAS-2279): Add callback tx hash

CHANGELOG.md, cmd/arc/services/callbacker.go, config/config.go, config/defaults.go, config/example_config.yaml, doc/README.md, internal/callbacker/mocks/processor_store_mock.go, internal/callbacker/processor.go, internal/callbacker/processor_routines.go, internal/callbacker/processor_routines_test.go, internal/callbacker/sender.go, internal/callbacker/sender_test.go, internal/callbacker/store/postgresql/fixtures/get_unsent/callbacker.transaction_callbacks.yaml, internal/callbacker/store/postgresql/migrations/000009_retries.down.sql, internal/callbacker/store/postgresql/migrations/000009_retries.up.sql, internal/callbacker/store/postgresql/postgres.go, internal/callbacker/store/postgresql/postgres_test.go, internal/callbacker/store/store.go, test/config/config.yaml
- Store retries in callbacker and update
- Only attempt each callback a maximum nr of times
Closes https://github.com/bitcoin-sv/arc/issues/959
=> feat(BPAAS-2341): callbacker max retries

.github/workflows/static-analysis.yaml, Dockerfile, go.mod, internal/metamorph/processor_test.go, internal/metamorph/server.go, internal/validator/defaultvalidator/default_validator.go
- Fix linted issue
- Upgrade Go version to 1.25.1
=> chore: upgrade go

cmd/broadcaster-cli/app/keyset/utxos/table.go, cmd/broadcaster-cli/app/utxos/broadcast/broadcast.go, cmd/broadcaster-cli/app/utxos/consolidate/consolidate.go, cmd/broadcaster-cli/app/utxos/create/create.go, internal/broadcaster/broadcaster.go, internal/broadcaster/broadcaster_test.go, internal/broadcaster/mocks/rate_broadcaster_mock.go, internal/broadcaster/mocks/utxo_client_mock.go, internal/broadcaster/multi_rate_broadcaster.go, internal/broadcaster/multi_rate_broadcaster_test.go, internal/broadcaster/rate_broadcaster.go, internal/broadcaster/rate_broadcaster_test.go, internal/broadcaster/utxo_consolidator.go, internal/broadcaster/utxo_consolidator_test.go, internal/broadcaster/utxo_creator.go, internal/broadcaster/utxo_creator_test.go, pkg/keyset/key_set.go, pkg/woc_client/woc_client.go, pkg/woc_client/woc_client_integration_test.go, pkg/woc_client/woc_client_test.go
- Extend time duration to get utxos from WoC
=> fix(BPAAS-2151): broadcaster cli

doc/README.md
- Fix typo in Scenario 2 of double spend flow documentation
=> docs: Double spend flow - fix scenario 2
